### ISSUE TITLE
关于分工和项目结构

### ISSUE THREAD

**Issue by osmanthuspeace** [NJUPT-SAST-Csharp/2023-WOC-Web#1]
### 先大概分析一下WOC的需求：
1. ”为client方向制作的客户端提供完善的应用服务接口“
--这显然是表示要两个组相互交流好，接口相关的文档我放在Apifox里了，有什么新的需求可以提出来然后直接在那里面改

2. “实现数据持久化。在服务宕机的情况下仍然能保存服务数据”
--就是要操作数据库，理论上呢，数据库应该放在某个大家都能访问到的服务器上，不过现在这个好像有点难度，先用本地的(?)

3. "根据http请求完成对词条的增删查改 "
--这个好办，放在Controller里，数据从Service里获取

4. “能够根据http请求判断用户身份，返回合理的内容”
--在Service层是有专门的TokenProvider来实现的(如果用jwt的话)，当然还有很多其他方式

5. “实现词条分类功能”
--可以放在Entry的服务里，而且有分类就要有搜索（

6. “实现用户登录与注册功能”
--基本的东西，重要的是身份验证

7. “实现允许多名用户协作编辑词条的功能”
--大概是要实时通信(?)

### 项目结构
根据🦊昨天的课和client方向的图，我姑且画了个项目结构的草图:

![proj1](https://github.com/NJUPT-SAST-Csharp/2023-WOC-Web/assets/146796167/ea81d982-325a-4357-abc2-2d8640921e4d)

![proj2](https://github.com/NJUPT-SAST-Csharp/2023-WOC-Web/assets/146796167/2f923e6d-8130-4530-b111-f8fcf0504432)

（都协作编程了，DI，IoC这种肯定是要有的）

### 分工
所以说到分工，我觉得可以分为：
**1.数据库 2.user的服务 3. entry的服务 4. 身份验证** 
其实分起来比较清楚，但是其中的事有很多，分的太细的话耦合度又太高，比如身份验证和登录的实现是分不开的。具体的方法看看Apifox里面，或者看图，因为真正做起来是要自己写Interface给别人的；

如果大家觉得没什么问题的话，就可以选一个开工了，我觉得可以先做起来，先完成增删查改等这样基础的任务（能跑就好），然后再一起讨论一下有难度的技术

还是要多交流沟通！

**Comment by losersandfox** [comment]
问一下，现在写的demo是不是就用本地文件的静态数据做测试就可以了

**Comment by osmanthuspeace** [comment]
> 问一下，现在写的demo是不是就用本地文件的静态数据做测试就可以了

目前可以这样，不过最好去用一下数据库

**Comment by losersandfox** [comment]
话说现在分工问题明确了吗

**Comment by losersandfox** [comment]
目前还有哪部分还没开工

**Comment by osmanthuspeace** [comment]
> 目前还有哪部分还没开工

大家还没有明确的说自己要做哪部分，所以项目还没开始（
