### ISSUE TITLE
Bug: PostEntry时不会消除重复的Tag

### ISSUE THREAD

**Issue by Shirasagi0012** [NJUPT-SAST-Csharp/2023-WOC-Web#19]
![image](https://github.com/NJUPT-SAST-Csharp/2023-WOC-Web/assets/23011330/92feebfe-9fbc-4579-a3dd-530080d53ae8)

只需要在PostEntry时加一个.Distinct()就完事了，LINQ真香（

不知道UpdateEntry会不会出这个问题，你也可以加一个提前规避下

**Comment by osmanthuspeace** [comment]
天哪我竟然完全没考虑到这一点！现在好了

**Comment by Shirasagi0012** [comment]
现在已经开始对自己写的Core项目进行全面debug了唉唉
今晚终于可以开始处理界面相关的东西了
